[package]
name = "extension-perlicascript"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
perlica-compiler = { path = "../../perlicascript/crates/compiler" }
perlica-runtime = { path = "../../perlicascript/crates/runtime-lib" }
extension = { path = "../extension" }
gpui = { path = "../gpui" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1"
log = "0.4"
