# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/zixiao-labs/Kaltsit-Esperanta/discussions/new?category=feature-requests
    about: To request a feature, open a new discussion under one of the appropriate categories.
  - name: Discussions
    url: https://github.com/zixiao-labs/Kaltsit-Esperanta/discussions
    about: Ask questions or chat with maintainers and other users in our GitHub Discussions.
