//! Wuling DevOps HTTP API client.
//!
//! The bulk of this module is auto-generated by `progenitor` from
//! `crates/ama10/api/wuling-openapi.yaml`. Hand-written extensions (auth flow
//! glue, retry/backoff, etc.) belong in this file alongside the `generated`
//! sub-module so they aren't clobbered on the next regeneration.
//!
//! To regenerate after the upstream OpenAPI spec changes:
//!
//! ```text
//! script/regen-wuling-api.sh
//! ```

mod generated;

pub use generated::*;
