[package]
name = "browser_ui"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/browser_ui.rs"
doctest = false

[dependencies]
anyhow.workspace = true
async_host_runtime.workspace = true
extension_cef.workspace = true
gpui.workspace = true
log.workspace = true
project.workspace = true
schemars.workspace = true
serde.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-video.workspace = true
