[package]
name = "async_host_runtime"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/async_host_runtime.rs"
doctest = false

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
futures.workspace = true
parking_lot.workspace = true

[dev-dependencies]
smol.workspace = true
